### ISSUE TITLE
is this going to be updated for new version of WindowsGSM?

### ISSUE THREAD

**Issue by drupi79** [Kickbut101/WindowsGSM.Factorio#1]
currently fails install on WindowsGSM 1.22.2 will this be updated to work with 1.22.2?

**Comment by Kickbut101** [comment]
> currently fails install on WindowsGSM 1.22.2 will this be updated to work with 1.22.2?

Works fine for me, what version of WindowsGSM do you mean? 

Also did you follow all the steps involved to get this to work?
https://github.com/Kickbut101/WindowsGSM.Factorio

**Comment by drupi79** [comment]
I did follow the instructions and it fails to install the plugin itself not the game.

**Comment by Kickbut101** [comment]
> I did follow the instructions and it fails to install the plugin itself not the game.

Fixed now, good catch and my bad! Thank you!! 

1b81e02aa7dbac32c3f22df3031c51ff771ed61a

**Comment by drupi79** [comment]
Welcome Man and thanks, your plugin is going to make my life a ton easier!
